```{r dgp, include = FALSE}
library(exams)
library(magrittr)
library(readxl)
library(writexl)
library(knitr)
library(statBasics)
library(tidyverse)
options(scipen = 999) #prevent scientific notation

# tamanho da amostra
tam <- 20:30 |> sample(1)

# desvio padrão da população
s <- 20:30 |> sample(1)

# média da população
m <- 50:100 |> sample(1)

amostra <- rnorm(tam, m, s)

ic_small <- ci_1pop_norm(amostra, sd_pop = s, conf_level = 0.90) |>
    round(2)
ic_large <- ci_1pop_norm(amostra, sd_pop = s, conf_level = 0.99) |>
    round(2)
```

Question
========
Conforme vimos em sala, intervalos de confianças com coeficiente de confianças maiores têm tamanhos maiores, ou seja, quanto maior o coeficiente de confiança maior é a _margem de erro_.

Considere $X \sim N(\mu, `r s^2`)$ e suponha que coletamos uma amostra com $`r tam`$ observações. Um pesquisador construiu dois intervalos de confiança (intervalo de confiança - Z): um coeficiente de confiança com $90\%$ e outro com coeficiente de confiança $99\%$. Neste contexto, marque apenas as alternativas **CORRETAS**.
  
Answerlist
----------
* O Intervalo de confiança $(`r ic_small$lower_ci`, `r ic_small$upper_ci`)$ foi construído com coeficiente de confiança $\gamma = 90\%$.
* O Intervalo de confiança $(`r ic_large$lower_ci`, `r ic_large$upper_ci`)$ foi construído com coeficiente de confiança $\gamma = 90\%$.
* O Intervalo de confiança $(`r ic_large$lower_ci`, `r ic_large$upper_ci`)$ foi construído com coeficiente de confiança $\gamma = 99\%$.
* O Intervalo de confiança $(`r ic_small$lower_ci`, `r ic_small$upper_ci`)$ foi construído com coeficiente de confiança $\gamma = 99\%$.

Solution
========
Answerlist
----------
* CORRETA.
* FALSA. O Intervalo de confiança $(`r ic_large$lower_ci`, `r ic_large$upper_ci`)$ foi construído com coeficiente de confiança $\gamma = 99\%$
* CORRETA.
* FALSA. O Intervalo de confiança $(`r ic_small$lower_ci`, `r ic_small$upper_ci`)$ foi construído com coeficiente de confiança $\gamma = 90\%$.

Meta-information
================
exname: icLargura
extype: mchoice
exsolution: 1010
exshuffle: TRUE