---
title: "Lista de exercícios"
output: bookdown::html_notebook2
editor_options: 
  chunk_output_type: console
---

## Used packages

```{r}
library(openxlsx)
library(latex2exp)
library(xtable)
library(readr)
library(readxl)
library(tidyverse)
```

## Table from exercise 8-40 from Montgomery

```{r}
x <- c( 8.24,
 8.25,
 8.20,
 8.23,
 8.24,
8.21,
 8.26,
 8.26,
 8.20,
 8.25,
8.23,
 8.23,
 8.19,
 8.28,
 8.24) %>% matrix(nrow = 5)

xtable(x, caption = "Hastes de metal usadas em sistema de suspensão de automóveis.",
       label = "tab:hastes-metal-suspensao",
       digits = 2, align = rep("c", ncol(x)+1)) %>% 
  print.xtable(booktabs = T,
               format.args = list(decimal.mark = ","),
               include.rownames = F, include.colnames = F)

```

## Table for the exercise 8-57

```{r}
x <- c(5.47,
 5.37,
 5.38,
 4.63, 5.37, 3.74, 3.71, 4.96, 4.64, 5.11, 5.65,
5.39,
 4.16,
 5.62,
 4.57, 4.64, 5.48, 4.57, 4.57, 4.51, 4.86, 4.56,
4.61,
 4.32,
 3.98,
 5.70, 4.15, 3.98, 5.65, 3.10, 5.04, 4.62, 4.51,
4.34,
 4.16,
 4.64,
 5.12, 3.71, 4.64, NA) %>% matrix(nrow = 5)

xtable(x, caption = "pH na chuva no Condado Ingham, Michigan.",
       label = "tab:ph-ingham",
       digits = 2, align = rep("c", ncol(x) + 1)) %>% 
  print.xtable(booktabs = T,
               format.args = list(decimal.mark = ","),
               include.rownames = F, include.colnames = F)

```

## Tabela for the exercise in 8-56

```{r}
x <- c(22.2,
 24.7,
 20.9,
 26.0,
 27.0,
24.8,
 26.5,
 23.8,
 25.6,
 23.9) %>% matrix(nrow = 2)

xtable(x, caption = "Nível de aminoácido (Lysine) de farejo de soja.",
       label = "tab:lysine-farelo-soja",
       digits = 2, align = rep("c", ncol(x) + 1)) %>% 
  print.xtable(booktabs = T,
               format.args = list(decimal.mark = ","),
               include.rownames = F, include.colnames = F)

```

