---
title: "Codigo para os exercícios"
output: bookdown::html_notebook2
editor_options: 
  chunk_output_type: console
---

## Used packages

```{r}
library(openxlsx)
library(readxl)
library(writexl)
library(latex2exp)
library(xtable)
library(tidyverse)
```

## Data from exercise 9-65 (Montgomery)

```{r}
x <- c(
 131.15, 130.69, 130.91, 129.54, 129.64,
 128.77, 130.72, 128.33, 128.24, 129.65, 130.14, 129.29,
128.71, 129.00, 129.39, 130.42, 129.53, 130.12, 129.78,
130.92
) %>% matrix(ncol = 5)

xtable(x, caption = "Quantidade de sódio nos cereais matinais em miligramas.",
       label = "tab:cereal-matinal",
       digits = 2, 
       align = rep("c", ncol(x) + 1)) %>% 
  print.xtable(booktabs = T, format.args = list(decimal.mark = ","),
               include.rownames = F, include.colnames = F)
```

## Simulating data simular to exercise 9-90 (Montgomery)

```{r}
set.seed(1235813)
n <- 300
p <- 98 / 275 
amostra <- rbinom(n, 1, prob = p)
a <- 0.05

lower <- (-1.96  / (2 * sqrt(n)) + mean(amostra)) %>% round(6)
upper <- (1.96  / (2 * sqrt(n)) + mean(amostra)) %>% round(6)


```

